name: Setup environment

inputs:
  anchor:
    description: The Anchor version to install
  cache:
    description: Enable caching
    default: "true"
  node:
    description: The Node.js version to install
    required: true
  solana:
    description: The Solana version to install

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Install Solana
      if: ${{ inputs.solana != '' }}
      uses: metaplex-foundation/actions/install-solana@v1
      with:
        version: ${{ inputs.solana }}
        cache: ${{ inputs.cache }}
    - name: Install Anchor
      if: ${{ inputs.anchor != '' }}
      uses: metaplex-foundation/actions/install-anchor-cli@v1
      with:
        version: ${{ inputs.anchor }}
        cache: ${{ inputs.cache }}
